# Generated by Django 5.2.14 on 2026-05-28 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NormalizedRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('original_row_id', models.CharField(blank=True, help_text='Reference to original row in source', max_length=100)),
                ('activity_type', models.CharField(choices=[('FUEL', 'Fuel Combustion'), ('ELECTRICITY', 'Electricity Consumption'), ('FLIGHT', 'Business Flight'), ('HOTEL', 'Hotel Stay'), ('GROUND_TRANSPORT', 'Ground Transportation'), ('PROCUREMENT', 'Procurement/Upstream')], max_length=100)),
                ('scope', models.CharField(choices=[('SCOPE1', 'Scope 1'), ('SCOPE2', 'Scope 2'), ('SCOPE3', 'Scope 3')], max_length=20)),
                ('amount', models.FloatField(help_text='Normalized amount in CO2e')),
                ('original_amount', models.FloatField(blank=True, help_text='Original amount before conversion', null=True)),
                ('original_unit', models.CharField(help_text="Original unit (e.g., 'gallons', 'kWh', 'miles')", max_length=50)),
                ('normalized_unit', models.CharField(default='kg CO2e', help_text='Normalized unit (kg CO2e)', max_length=50)),
                ('emission_factor', models.FloatField(blank=True, help_text='Emission factor used for conversion', null=True)),
                ('emission_factor_source', models.CharField(blank=True, help_text='Source of emission factor', max_length=255)),
                ('start_date', models.DateField(help_text='Start date of activity period')),
                ('end_date', models.DateField(help_text='End date of activity period')),
                ('facility_code', models.CharField(blank=True, help_text='Plant/facility identifier', max_length=100)),
                ('facility_name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('suspicious_flag', models.BooleanField(default=False)),
                ('suspicious_reason', models.TextField(blank=True, help_text='Why this record was flagged as suspicious')),
                ('review_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('reviewed_by', models.CharField(blank=True, max_length=100)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('source_reference', models.CharField(help_text='Reference back to source document/system', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('raw_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='normalized_records', to='ingestion.rawdatafile')),
                ('source', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='records', to='ingestion.datasource')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='tenants.tenant')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'review_status'], name='emissions_n_tenant__63bc65_idx'), models.Index(fields=['tenant', 'start_date'], name='emissions_n_tenant__854d18_idx'), models.Index(fields=['scope', 'activity_type'], name='emissions_n_scope_0fb878_idx')],
            },
        ),
    ]
