# Generated by Django 5.2.14 on 2026-05-28 15:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='normalizedrecord',
            name='amount',
            field=models.FloatField(default=0, help_text='Normalized amount in CO2e', null=True),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='end_date',
            field=models.DateField(default=datetime.date.today, help_text='End date of activity period'),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='original_unit',
            field=models.CharField(default='', help_text="Original unit (e.g., 'gallons', 'kWh', 'miles')", max_length=50),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='source_reference',
            field=models.CharField(default='', help_text='Reference back to source document/system', max_length=255),
        ),
        migrations.AlterField(
            model_name='normalizedrecord',
            name='start_date',
            field=models.DateField(default=datetime.date.today, help_text='Start date of activity period'),
        ),
    ]
