# Generated by Django 5.2.14 on 2026-05-28 14:37

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('emissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('change_type', models.CharField(choices=[('REVIEW', 'Review Status Change'), ('EDIT', 'Field Edit'), ('FLAG', 'Suspicious Flag'), ('CREATE', 'Record Created'), ('DELETE', 'Record Deleted')], max_length=20)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('changed_by', models.CharField(help_text='Username or identifier of person/system making change', max_length=100)),
                ('changed_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='emissions.normalizedrecord')),
            ],
            options={
                'ordering': ['-changed_at'],
                'indexes': [models.Index(fields=['record', 'changed_at'], name='audit_audit_record__26e2a7_idx')],
            },
        ),
    ]
